repos:
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.730
  hooks:
    - id: mypy
- repo: https://github.com/pre-commit/mirrors-isort
  rev: v4.3.21
  hooks:
  - id: isort
    args: ['-up', '--multi-line', '3', '-tc', '-l', '88', '-rc']
- repo: git@github.com:humitos/mirrors-autoflake.git
  rev: v1.1
  hooks:
  - id: autoflake
    args: ['--in-place', '-r', '--remove-all-unused-imports']
- repo: https://github.com/ambv/black
  rev: stable
  hooks:
  - id: black
    language_version: python3.7

